<?php

namespace app\models\ar\base;

use Yii;

/**
 * This is the model class for table "tags".
 *
 * @property integer $id
 * @property integer $user
 * @property string $title
 * @property integer $parent_id
 *
 * @property User $user0
 * @property TagsResult[] $tagsResults
 */
class Tags extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tags';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user', 'parent_id'], 'integer'],
            [['title'], 'string', 'max' => 200],
            [['title'], 'required'],
            [['user'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user' => 'User',
            'title' => 'Title',
            'parent_id' => 'Parent ID',
        ];
    }

    public function beforeValidate()
    {
        $this->user = \Yii::$app->user->id;
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser0()
    {
        return $this->hasOne(User::className(), ['id' => 'user']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTagsResults()
    {
        return $this->hasMany(TagsResult::className(), ['tag_id' => 'id']);
    }
}
