<?php
/**
 * Created by PhpStorm.
 * User: ialeksandrychev
 * Date: 27.04.16
 * Time: 14:53
 */

namespace app\models\ar;


class Projects extends \app\models\ar\base\Projects
{

    public function beforeSave($insert)
    {
        $this->user = \Yii::$app->user->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}