<?php
/**
 * Created by PhpStorm.
 * User: ialeksandrychev
 * Date: 06.06.16
 * Time: 14:41
 */

namespace app\models\logic;


use app\models\ar\Projects;
use yii\base\Model;

class AutocompleteForm extends Model
{
    public $text;
    public $project_id;

    public function init()
    {
        $this->project_id = \Yii::$app->request->get('project_id');
        if(!empty($this->project_id)){
            $project = Projects::findOne(['id' => $this->project_id]);
            $this->text = $project->text;
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['text'], 'safe'],
            [['text'], 'required'],
        ];
    }

    public function save()
    {
        $project = Projects::findOne(['id' => $this->project_id]);
        $project->text = $this->text;
        $project->save();
    }


}